apiVersion: v1
kind: Service
metadata:
  name: nvne-front
  labels:
    app: nvne-front
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nvne-front
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvne-front
  namespace: default
  labels:
    app: nvne-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nvne-front
  template:
    metadata:
      labels:
        app: nvne-front
    spec:
      containers:
      - name: nvne-front
        image: gcr.io/indigo-almanac-283817/nvne-front:v3
        ports:
        - name: http
          containerPort: 80
