apiVersion: v1
kind: Service
metadata:
  name: nvne-front
  labels:
    app: nvne-front
spec:
  ports:
  - name: endpoint
    port: 80
    targetPort: 80
  selector:
    app: nvne-front
  type: LoadBalancer
