apiVersion: v1
kind: Namespace
metadata:
  name: nvne
---
apiVersion: v1
kind: Service
metadata:
  name: nvne-front
  namespace: nvne
  labels:
    app: nvne-front
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: nvne-front
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvne-front
  namespace: nvne
  labels:
    app: nvne-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nvne-front
  template:
    metadata:
      labels:
        app: nvne-front
    spec:
      containers:
      - name: nvne-front
        image: gcr.io/stellar-spark-300508/nvne-front:0.0.25
        ports:
        - name: http
          containerPort: 80
